### PR TITLE
flucca/feat/index carbon styles

### LINKED ISSUE #450: Index Carbon Styles
To do with system squad:
- [x] Are we indexing v11 only or any need to index v10 assets?
- [x] Work with system squad to identify the base library (`carbon-components` code package or `@carbon/styles` or do we really need a `@carbon/base` or `@carbon/spec` package?)
- [x] Determine indexing strategy (one or many `carbon.yml` files per library)
- [x] Determine the source of truth for what needs indexed (website or Storybook)

To do:
- [x] We make a pass and identify gaps
- [ ] Work with system squad to fill gaps
- [ ] Register library in platform

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #450 

#### Testing / reviewing
 
Pull changes and run with `INDEX_ALL=1` in `local.env` file , you should see carbon styles listed as a library and have the components show up both in the catalog and library details

### CODE REVIEW

**Comment by francinelucca** [comment]
@jdharvey-ibm commit history is broken here as well, I'm definitely doing something wrong

**Comment by francinelucca** [comment]
Marking as ready for review, just waiting for these few thumbs from design: 
CopyButton
Combobox
TextArea
TimePicker
TooltipDefinition
Treeview
Theme
PaginationNav

**Review by jharvey10 — DISMISSED** [review]

**Comment by francinelucca** [comment]
Ready!

**Review by andreancardona — APPROVED** [review]
yay!!

**Review by alisonjoseph — APPROVED** [review]
🥳

**Pull request merged**
