### PR TITLE
feat(web-app): add mdx page table

### LINKED ISSUE #561: Render markdown table
Create table component to match styles in Gatsby theme

https://gatsby-theme-carbon.vercel.app/components/markdown#tables
https://github.com/carbon-design-system/gatsby-theme-carbon/tree/main/packages/gatsby-theme-carbon/src/components/PageTable

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #561 

#### Testing / reviewing

http://localhost:3000/mdx/table
https://gatsby-theme-carbon.vercel.app/components/markdown#tables

### CODE REVIEW

**Review by francinelucca — DISMISSED** [review]
LGTM!

**Review by francinelucca — COMMENTED** [review]
this LGTM! ❤️ . do we need to add a story to this? or not?

**Comment by alisonjoseph** [comment]
This component translates markdown, so not sure there is a way to add a story for this that would make sense or be useful?

**Review by francinelucca — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
lookss good 🔥

**Pull request merged**
