### PR TITLE
feat(web-app): add banner component

### LINKED ISSUE #1365: Develop crosslink banner for homepage
Related design issue: https://github.com/carbon-design-system/carbon-platform/issues/1235

For the v1 release, we need a banner on the homepage that will link the [Next](https://next.carbondesignsystem.com/) platform site out to the [Main](https://carbondesignsystem.com/) Carbon site. 

**Interactions:**
- Banner **only** exists on the homepage
- Banner is **not** sticky and scrolls away

**Content**
- The exact content is still TBD. @aubrey-oneal to finalize

## Spec
[Figma file](https://www.figma.com/file/H3kWgBYKdMzov7LIZ1BlHa/Next-crosslinks?node-id=67%3A6733)

Group Next

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #1365

#### Changelog

**New**

- banner component

#### Testing / reviewing

Make sure banner only shows on homepage and matches spec. (discussed in slack that it will stay sticky at the top)
http://localhost:3000/

### CODE REVIEW

**Review by francinelucca — CHANGES_REQUESTED** [review]
This is looking so good 😻 
The spec kind of looks like the whole thing is clickable on mobile and the arrow kind of hangs right? I could be wrong just double checking 
image
image

**Comment by alisonjoseph** [comment]
updated @francinelucca

**Review by andreancardona — APPROVED** [review]
tested and looks good!

**Review by francinelucca — APPROVED** [review]
💃

**Pull request merged**
