### PR TITLE
fix: update type tokens to v11

### PR DESCRIPTION
**Pull request by alisonjoseph**
#### Changelog

**Changed**

- Swapped all v10 type tokens for correct v11 tokens

#### Testing / reviewing

This shouldn't change anything visually.

### CODE REVIEW

**Comment by francinelucca** [comment]
visuals LGTM, found one more heading in `catalog-list.module.scss` that probably needs update as well: 
image
Also, not sure if motion params need update?

**Review by francinelucca — COMMENTED** [review]
visuals LGTM, found one more heading in `catalog-list.module.scss` that probably needs update as well: 
image
Also, not sure if motion params need update?

**Comment by alisonjoseph** [comment]
Good catch, updates @francinelucca, and motion tokens are correct I believe.

**Review by francinelucca — APPROVED** [review]
🎉

**Review by andreancardona — APPROVED** [review]
🎉

**Pull request merged**
