### PR TITLE
feat(web-app): treeview integration with sidenav

### LINKED ISSUE #688: Extend navigation to support open/closed sections
Our navigation needs to support the ability to open/close sections using treeview.

https://user-images.githubusercontent.com/2753488/166928344-21cade2f-8664-467b-8d8e-a00dc81ef34d.mov

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #688 

#### Testing / reviewing

create services/web-app/pages/test.js file:
```
/*
 * Copyright IBM Corp. 2021, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { NextSeo } from 'next-seo'
import { useContext, useEffect } from 'react'

import PageNotFound from '@/components/page-not-found'
import { testNavData } from '@/data/nav-data'
import { LayoutContext } from '@/layouts/layout'

const FourOhFour = () => {
  const { setNavData } = useContext(LayoutContext)

  useEffect(() => {
    setNavData(testNavData)
  }, [setNavData])

  const seo = {
    title: 'Page not found'
  }

  return (
    <>
      <NextSeo {...seo} />
      <PageNotFound />
    </>
  )
}

export default FourOhFour
```

add to services/web-app/data/nav-data.js:
```
export const testNavData = [
  {
    title: 'Guidelines',
    items: [
      {
        path: '/assets/guidelines/2x-grid/overview',
        title: '2x Grid'
      },
      {
        path: '/assets/guidelines/accessibility/overview',
        title: ' Accessibility'
      },
      {
        path: '/assets/guidelines/content/overview',
        title: ' Content'
      },
      {
        path: '/assets/guidelines/color/overview',
        title: ' Color'
      },
      {
        path: '/assets/guidelines/icons/library',
        title: ' Icons'
      },
      {
        path: '/assets/guidelines/pictograms/library',
        title: ' Pictograms'
      },
      {
        path: '/assets/guidelines/motion/overview',
        title: ' Motion'
      },
      {
        path: '/assets/guidelines/spacing/overview',
        title: ' Spacing'
      },
      {
        path: '/assets/guidelines/themes/overview',
        title: ' Themes'
      },
      {
        path: '/assets/guidelines/typography/overview',
        title: ' Typography'
      }
    ]
  },
  {
    path: '/assets/libraries',
    title: 'Libraries'
  },
  {
    title: 'Catalogs',
    isSection: true,
    items: [
      {
        path: type.component.path,
        title: type.component.namePlural
      },
      // remove elements for the first release
      // {
      //   path: type.element.path,
      //   title: type.element.namePlural
      // },
      {
        path: type.function.path,
        title: type.function.namePlural
      },
      {
        path: type.pattern.path,
        title: type.pattern.namePlural
      },
      {
        path: type.template.path,
        title: type.template.namePlural
      }
    ]
  },
  {
    title: 'Collections',
    isSection: true,
    items: [
      {
        path: '/assets/data-visualization',
        title: 'Data visualization'
      }
    ]
  }
]
```

test sideNav in: http://localhost:3000/test
also make sure library sideNav still renders as expected: http://localhost:3000/assets/carbon-charts

### CODE REVIEW

**Review by andreancardona — DISMISSED** [review]
Looks good!

**Comment by francinelucca** [comment]
> This is looking great! I added in some mdx files from my other PR to test, do we want to add the functionality to have the nav open when you land on a page to this PR, along with the active state? It doesn't appear to be working as is.

oh yeah, nice catch! looking into it

**Review by andreancardona — DISMISSED** [review]

**Review by alisonjoseph — APPROVED** [review]
LGTM! Tested with real pages from my content PR. 🥳

**Review by andreancardona — APPROVED** [review]
🔥 🔥

**Pull request merged**
