### PR TITLE
fix(web-app): proxy server conversion to esm

### LINKED ISSUE #969: Web App: Can't run proxy server on dev mode
**Description**

Error running proxy server on dev environment

**Steps to reproduce**

from services/web-app:

1. `npm run start:proxy`
See error:
image

### PR DESCRIPTION
**Pull request by jdharvey-ibm**
Closes #969

### CODE REVIEW

**Review by francinelucca — APPROVED** [review]
LGTM! confirmed can run access app through server 💃 . 
No changes required in web-app/Dockerfile from renaming the file? I'm assuming no but double-checking

**Comment by jdharvey-ibm** [comment]
@francinelucca good call. There's one change I missed in the esbuild file. I'll update that now.

**Comment by andreancardona** [comment]
@jdharvey-ibm 

Should I be able to see the app?  👀 

Screen Shot 2022-07-21 at 1 35 50 PM

**Comment by jdharvey-ibm** [comment]
@andreancardona If you're just running `start:proxy`, then you won't see the app. The [docs over here](https://carbon-design-system.github.io/carbon-platform/services-web-app.html#proxy-server) give some info about how the proxy-server relates to the web app, but the net is that you'd need to run both the dev server *and* the proxy server, and then navigate to localhost:8080 to see the web-app *through* the proxy.

**Comment by andreancardona** [comment]
> he proxy-server relates to the we

okay thank you :)

**Review by andreancardona — APPROVED** [review]
🔥

**Pull request merged**
