### PR TITLE
1123 common mdx error documentation updates

### LINKED ISSUE #1123: Common MDX error documentation updates
**Summary**

- What route inside platform should the common mdx errors page live? Ex: next.carbondesignsystem.com/common-mdx-errors
- What should this page format look like? 
Sample content: https://github.com/carbon-design-system/carbon-platform/blob/e9372e24aa1b0504a0f11bf68e9a37ef7cf6de7d/services/web-app/pages/common-mdx-errors.mdx
image
image

**Job stories**

What value will this deliver?

1. When my authored content on platform has an error, I want to get more information on the error, so I can fix it.

**Acceptance criteria**

What requirements must be met to complete this request?

- [ ] determine desired url for page content to live in
  - we want this to live in storybook next to the mdx components themselves so it is "in context"
- [ ] design pattern for a problem/solution (i.e. how should the header/title look? should it start with text or an image? what is the general sentence structure of a solution?) (#1176)

**TODO**

- [ ] Incorporate design updates from #1176 into existing content
- [ ] Move page to (eventually) deployed storybook
  - Q: is this the mdx-components storybook? or the general platform storybook?

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #1123

Implements new styles for common mdx errors page.

Can't put this into SB yet since most of the components used in the page haven't been migrated to `mdx-components` yet, will put on storybook once #1103 completes (Tracked Here #1430)

Redline: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/Platform_MDXerrors?node-id=317%3A11968

Note: 
- InlineError and FullPageError are both hanging left, this is documented in issue #1364 
- There's this weird overlap on the inline code and the text here http://localhost:3000/common-mdx-errors#component-not-rendering, it's also on prod https://next.carbondesignsystem.com/common-mdx-errors#inline-styles not sure what's happening here 🤷‍♀️ , tracking in #1384

#### Changelog

**Changed**

- Converted common errors mdx page into a .js page to prepare for storybook migration, also added styling according to redlines pattern

#### Testing / reviewing

http://localhost:3000/common-mdx-errors

### CODE REVIEW

**Review by andreancardona — COMMENTED** [review]
Seeing some weird sizes on different MD and SM breakpoints - let me know your thoughts! :) 
Screen Shot 2022-10-06 at 9 48 49 AM
Screen Shot 2022-10-06 at 9 50 28 AM

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Small missing token, I'm also seeing the incorrect col width for the notifications at sm/md, but possibly unrelated to this PR? They should match the paragraph width I believe.

**Comment by francinelucca** [comment]
> Small missing token, I'm also seeing the incorrect col width for the notifications at sm/md, but possibly unrelated to this PR? They should match the paragraph width I believe.

thanks! will fix. Col issues are general and documented here #1364

**Review by alisonjoseph — APPROVED** [review]

**Comment by francinelucca** [comment]
@andreancardona fixed columns, the small screen white space issue is documented in #1384

**Review by andreancardona — APPROVED** [review]
looks good! 💯

**Pull request merged**
