### PR TITLE
feat(web-app): add global content wrapper for consistent spacing

### LINKED ISSUE #1215: Investigate global wrapper component for page padding-top
Looks like we lost the correct padding at the top of the page when switching from mdx to js page. Wondering if we should move this style to a global wrapper, although may add incorrect spacing to other pages if we do that. Can probably look at that in a different issue unless its an easy fix.

Screen Shot 2022-09-01 at 9 56 19 AM

Screen Shot 2022-09-01 at 9 58 20 AM

Everything else is running / working great!

_Originally posted by @alisonjoseph in https://github.com/carbon-design-system/carbon-platform/pull/1205#pullrequestreview-1093558542_

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #1215

New `ContentWrapper` component.
  - The intention is for any page content, mdx or otherwise to be wrapped in this component for consistent top spacing. 

This component was NOT added to any of the catalog pages for now, those pages have a different top spacing because the search bar is the first element. 

#### Testing / reviewing
Check mdx pages, js page and remote mdx pages, pages with/without tabs etc. 

http://localhost:3000/elements/icons/library
http://localhost:3000/libraries/carbon-react/latest/assets/accordion
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/style
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/usage
http://localhost:3000/libraries/carbon-react/latest/assets/accordion/accessibility
http://localhost:3000/about-carbon/releases
http://localhost:3000/about-carbon/articles
http://localhost:3000/elements/color/usage
http://localhost:3000/libraries/carbon-components-angular/latest
http://localhost:3000/libraries/carbon-components-angular/latest/design-kits
http://localhost:3000/libraries/carbon-components-angular/latest/pages/tutorial/step-2

### CODE REVIEW

**Review by jdharvey-ibm — APPROVED** [review]
I didn't test it locally, but the code changes look good to me 👍

**Review by francinelucca — CHANGES_REQUESTED** [review]
This is GREAT 👯‍♀️ , just one thing: 
Looks like the first item rule is messing with the dashboard item spacing:
image
image
---

**Comment by alisonjoseph** [comment]
@francinelucca good catch! I updated it to only zero out the margin-top for first elements, this way we can preserve any custom spacing needed with padding. Currently all the core mdx components use margin-top to space things out, so this should work.

**Review by francinelucca — APPROVED** [review]
LGTM!

**Pull request merged**
