### PR TITLE
fix(web-app): fix page not found vertical spacing

### LINKED ISSUE #1778: 404 content needs vertical spacing
**Description**

> Tell us more about the problem that you're running into. What did you see? What did you expect to
> see?

We need to add some vertical spacing.

image

**Steps to reproduce**

> How do we reproduce the error? Please be as specific as you can.

1. https://next.carbondesignsystem.com

**Solution**

Looking at this. Not sure what this declaration block is currently doing: https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/components/page-not-found/page-not-found.module.scss#L17

I think we need 64px spacing on desktop:
image

And 32px spacing on phone:
image

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #1778 

#### Changelog

**Changed**

- Added css styling to fix vertical spacing in page not found component
- Minor HTML restructure changes in page not found component 

#### Testing / reviewing
Verify vertical spacing in lg/sm breakpoints:
image
image

### CODE REVIEW

**Comment by mattrosno** [comment]
Thanks @francinelucca!

@aagonzales @kingtraceyj can you review the screenshots here? Should there be space between the two sentences? Or should there just be space around the copy block like here: https://github.com/carbon-design-system/carbon-platform/issues/1778

**Comment by mattrosno** [comment]
Design guidance here: https://ibm-studios.slack.com/archives/C06P07KPAUR/p1709913167917949

**Comment by francinelucca** [comment]
Ready for re-rev

**Review by aagonzales — APPROVED** [review]
Looks good

**Review by mattrosno — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
