### PR TITLE
feat: prep main branch for production deploy

### LINKED ISSUE #466: March release prod deployment
Merge

- [x] https://github.com/carbon-design-system/carbon-platform/pull/406

Clean up

- [x] All catalog items take you to asset detail pages (because from there we link to external docs)
- [x] Fix breadcrumb

Update

- [x] Add accessibility link to footer
- [x] Asset LP release copy for 0.2 with us accomplishing:

* Indexed charts, dotcom
* Collection to view only charts
* New data:
    * External docs links
    * Demo sites
    * Issue counts
* Navigation (page tabs, footer) and catalog improvements (more performant filtering, type tags)

- [x] Also update roadmap beyond 0.2

### PR DESCRIPTION
**Pull request by mattrosno**
Closes #466 

See issue for what's changed. See comment below for updated roadmap copy.

v0.1 is unchanged.

v0.2 description and bullets updated to what we accomplished.

Next week, we can add details for April and May as that firms up.

v1.0 bumped back to the June release, meaning we release at the end of June. Login moved to later release, and added more detail on what content and libraries are available.

v1.1 bumped back one month to July release, with login happening now and indexing of IBM internal libraries.

v2.0 still Q3, with telemetry moved to here from v1.1 for now.

The copy can be found here if anybody wants to copy and rewrite and share suggestions in comments. https://github.com/carbon-design-system/carbon-platform/blob/63d597b455ed8a0d2a85c6c6fda233d436dcabce/services/web-app/pages/assets/index.js

### CODE REVIEW

**Comment by mattrosno** [comment]
image

image

image

image

Image caption:

>v2.0 User experience: In this release, all external docs content has been fully migrated allowing the PALs to sunset. The team switcher will allow teams to view assets and documenation through the lens of their team.

**Review by alisonjoseph — APPROVED** [review]

**Comment by alisonjoseph** [comment]
Updated copy for the March release title

image

**Review by francinelucca — DISMISSED** [review]

**Comment by alisonjoseph** [comment]
waiting on image from @jeanservaas

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
~waiting on image~

**Review by alisonjoseph — APPROVED** [review]
Confirmed with Jeannie we don't need the image

**Review by francinelucca — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
