### PR TITLE
fix: add border to side nav

### LINKED ISSUE #291: Side nav needs a right border for asset landing page
### Browser

_No response_

### Description

The assets landing page has a right border on the side nav. We're using the Carbon side nav straight up. Do we need to add a border? If so, can that be a global thing so the border is always there and not only on the asset details page? Is this provided by Carbon or do we need to add that custom styling?

See:
image

### Steps to reproduce

image

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #291 

#### Changelog

**New**

- Border to sidenav

### CODE REVIEW

**Review by francinelucca — DISMISSED** [review]
LGTM! 🎉 
image

**Review by mattrosno — CHANGES_REQUESTED** [review]
I'm seeing the right border on mobile when the side nav is closed (1px light line left edge of viewport.)
image

**Comment by alisonjoseph** [comment]
@mattrosno updated to only show the border at large and above, confirmed that is consistent with current Carbon website.

**Review by francinelucca — APPROVED** [review]
Not seeing border in mobile anymore 🎉  
image

**Review by andreancardona — APPROVED** [review]
confirmed all looks good to merge! 💯

**Pull request merged**
