### PR TITLE
fix(web-app): display design only tag in library assets

### PR DESCRIPTION
**Pull request by francinelucca**
Fixes logical error on library assets page that prevented Design only tag from showing up 

#### Changelog

**Changed**

- services/web-app/pages/libraries/[host]/[org]/[repo]/[library]/[ref]/assets/index.js: fix if statement condition

#### Testing / reviewing

http://localhost:3000/libraries/carbon-charts/latest/assets: validate design tags
image

### CODE REVIEW

**Review by andreancardona — CHANGES_REQUESTED** [review]
@francinelucca I think we might want to change the tag to `Design only` @aubrey-oneal can you confirm?

**Comment by aubrey-oneal** [comment]
Unless it is a special vocab word, we'll always do sentence case.

So yes, it should be `Design only`

**Comment by francinelucca** [comment]
fixed! thanks!! @aubrey-oneal @andreancardona ✨

**Review by andreancardona — APPROVED** [review]
😎

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
