### PR TITLE
docs: update usage path docs to allow absolute url

### LINKED ISSUE #900: update scheme docs to allow for absolute and relative urls for library navData
related https://github.com/carbon-design-system/carbon/pull/11631

Need to update schema to allow for both relative and absolute urls for library navData

image

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #900 
Update library schema docs to allow both relative and absolute urls in `navData`

### CODE REVIEW

**Review by francinelucca — CHANGES_REQUESTED** [review]
docs LGTM, let's update packages/schemas as well?  (internal/validation/* and carbon-resources.schema.json)
image
image

**Comment by alisonjoseph** [comment]
updated @francinelucca

**Review by andreancardona — APPROVED** [review]
looks good!

**Review by francinelucca — APPROVED** [review]
💃

**Pull request merged**
