### PR TITLE
feat(web-app): render remote mdx

### LINKED ISSUE #321: Remote MDX functionality
A key aspect of the platform's content mesh is fetching markdown (MDX files) from remote GitHub repositories and rendering in the web app. Assuming we use https://github.com/hashicorp/next-mdx-remote, there are import / export caveats to consider: https://github.com/hashicorp/next-mdx-remote#import--export

This makes a lot of sense. When pulling in remote MDX content not coming from the carbon-platform repo, we can't control that content, and can't let MDX import and run arbitrary components. Also, when the MDX content is remote, it doesn't run through Webpack.

There are multiple remote mdx instances that can break the mdx rendering in-app as well, we need a process to handle those.

We'll need a scrubbing process so when we fetch MDX file content through GitHub's API, we clean it to remove/modify unwanted or unrenderable components.

There is also some media handling that needs to be done in order to safely and accurately load media such as images and videos.

So the platform can safely render it.

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #321 

#### New

- getRemoteMdxData function 
- RemoteMdxLoader component
- *temporary* github unoptimized image resolver <- this will be adressed in #693 
- Sample MDX page rendering from remote repo (hardcoded params)

#### Testing / reviewing

http://localhost:3000/samples/remote-mdx-test
https://carbondesignsystem.com/components/accordion/style

### CODE REVIEW

**Review by alisonjoseph — COMMENTED** [review]
This is working great!

Question, if we're using `next-mdx-remote` are we able to use that for local mdx files also instead of `@next/mdx`. I thought I read it was an either/or thing, could be out of scope for this PR, but not sure if we should look into that?

**Comment by francinelucca** [comment]
> This is working great!
> 
> Question, if we're using `next-mdx-remote` are we able to use that for local mdx files also instead of `@next/mdx`. I thought I read it was an either/or thing, could be out of scope for this PR, but not sure if we should look into that?

@next/mdx doesn't support remote loading, we *could* use next-mdx-remote for our local pages but then we'd have to create a .js page for each and use a getStaticProps method to import the mdx file and serialize the contents 🤔 (https://github.com/hashicorp/next-mdx-remote#examples) , not sure we'd want to do that?

**Review by alisonjoseph — APPROVED** [review]
> we could use next-mdx-remote for our local pages but then we'd have to create a .js page for each and use a getStaticProps method to import the mdx file and serialize the contents

@francinelucca hmm yea, if we'd have to do that for each page that doesn't seem like it would work.

**Review by andreancardona — APPROVED** [review]
🔥

**Comment by mattrosno** [comment]
This should have closed https://github.com/carbon-design-system/carbon-platform/issues/690 not the epic. Fixing now. NBD.

**Pull request merged**
