### PR TITLE
fix(web-app): reduce z-index for svg libraries

### LINKED ISSUE #958: z-index bug on icon/pictogram search
Screen Shot 2022-07-06 at 10 46 09 AM

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #958 

#### Testing / reviewing

http://localhost:3000/elements/icons/library
http://localhost:3000/elements/pictograms/library

### CODE REVIEW

**Comment by francinelucca** [comment]
@alisonjoseph changed to footer! thanksss

**Review by alisonjoseph — APPROVED** [review]
This fixes the issue 🥳 

Sidenote: is it weird to use a z-index named "footer", should we create our own set of z-indexes for platform? I believe the ones exported from Carbon were created specifically for modal, but I could be mistaken.

**Comment by francinelucca** [comment]
@alisonjoseph added a z-index map to our variables scss file and replaced all z-index.z() usage with that

**Review by alisonjoseph — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
tested and looks good!

**Pull request merged**
