### PR TITLE
fix: white space margin

### LINKED ISSUE #937: [mobile] Style bug - Remove white line on the right side of the leadspace banner
In mobile (safari and Chrome) a 1–2px white line shows up o the right edge of the G100 leadspace banner.
IMG_3262

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #937 
-  Removed scroll jumping
- All white margins at all breakpoints should be gone - should now look like this: 

Screen Shot 2022-07-06 at 5 49 48 PM

Screen Shot 2022-07-06 at 5 49 37 PM

### Medium breakpoint 

Screen Shot 2022-07-25 at 4 56 23 PM

## TESTING: 

- [ ] http://localhost:3000/

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
I'm still seeing a white line to the right of the banner/footer in Chrome. Wondering if it has something to do with the scrollbar width not being defined in chrome. 


Screen Shot 2022-07-07 at 2 47 49 PM

**Review by francinelucca — COMMENTED** [review]
Banner and Footer LGTM, I also see a small right white margin in the lighter areas of the page, is that ok? 
image

image

**Comment by andreancardona** [comment]
@francinelucca not seeing it 👀 let me know if you see it again?

**Comment by alisonjoseph** [comment]
I'm not seeing the white to the right, unless my eyes are playing tricks on me. Can we add some comments to the css on why we have the -1px/1px margins, this feels weird to me to have to add and would be good to explain why its there.

**Review by francinelucca — APPROVED** [review]
💃

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
