### PR TITLE
feat(web-app): add nested props to lists that are desendants of li

### LINKED ISSUE #351: Render nested lists with correct styles in MDX
We need to be able to pass in a prop to nested lists rendered with mdx to correctly pull in Carbon styles.

This is a bug because as-is, the bullets are wrong.

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #351 

😰 

#### Testing / reviewing

http://localhost:3000/mdx/nested-lists

### CODE REVIEW

**Review by alisonjoseph — COMMENTED** [review]
Ahhhh, you figured it out. 🥳  If its not too tricky, can we only have the grid/column component wrapping the list if its not nested?

**Comment by francinelucca** [comment]
> Ahhhh, you figured it out. 🥳 If its not too tricky, can we only have the grid/column component wrapping the list if its not nested?

Done!

**Review by alisonjoseph — DISMISSED** [review]
LGTM! @francinelucca I just pushed an update to `markdown.module.scss `to fix the nested spacing and make sure it matched the gatsby theme. Should be good now, but good to double check.

**Comment by francinelucca** [comment]
> LGTM! @francinelucca I just pushed an update to `markdown.module.scss `to fix the nested spacing and make sure it matched the gatsby theme. Should be good now, but good to double check.
Looks good, thanks!

**Review by alisonjoseph — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
Looks good! 🔥

**Pull request merged**
