### PR TITLE
fix(web-app): broken links

### LINKED ISSUE #1284: Broken links from v1 "test fest"
- [x] https://next.carbondesignsystem.com/about-carbon/how-carbon-works#carbon-maintainers
   -  Schema link should be https://next.carbondesignsystem.com/contributing/schema. No redirect needed as that first URL must have been used in a pre-v1 release.
- [x] https://next.carbondesignsystem.com/#how-pal-teams-can-prepare
   - Get started should be this URL: https://next.carbondesignsystem.com/contributing/schema.
- [x]  https://next.carbondesignsystem.com/designing/sketch#symbols
   - design guidelines should link  https://next.carbondesignsystem.com/elements/accessibility/overview
- [x] search our source for /elements/ to fix this and other links that could be wrong, from when we move Accessibility and Content out of Elements into Guidelines.
- [x] https://next.carbondesignsystem.com/designing/axure#releases
   - #carbon-axure-kit link should point to https://ibm-studios.slack.com/archives/CHJH2DKT8
- [x] https://next.carbondesignsystem.com/#search-asset-catalogs
   - Library catalog should link https://next.carbondesignsystem.com/libraries
- [x] https://next.carbondesignsystem.com/guidelines/accessibility/overview
   - Color contrast link missing -  https://marijohannessen.github.io/color-contrast-checker/
- [x] Update Get started link on homepage to Schema page https://next.carbondesignsystem.com/contributing/schema
- [x] Tutorials should link to Platform tutorials on https://next.carbondesignsystem.com/developing
- [x] - Under the `Local design kits` section for Carbon, the "design kit catalog" link directs you to the wrong page. It should direct to this page https://next.carbondesignsystem.com/design-kits instead.

### Carbon website broken/wrong links
- [x]  https://next.carbondesignsystem.com/guidelines/content/writing-style#pronouns The link to IBM Style pronouns is broken. It should direct to this link https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=grammar-pronouns instead.
- [x] https://carbondesignsystem.com/guidelines/content/writing-style#conversational-style   In the section Conversational style, the link is broken. It should direct to here https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=medium-conversational-style
- [x] https://next.carbondesignsystem.com/guidelines/content/overview#questions-and-feedback
   - There is a link bug in the Questions and Feedback section for the Carbon Slack channel. The link currently goes to the Content page but it needs to be this link instead https://ibm-studios.slack.com/messages/C0M053VPT/.

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #1284

#### Changelog

See issue for links fixed in this PR.

#### Testing / reviewing

Check that updated links are correct.

### CODE REVIEW

**Comment by mattrosno** [comment]
@alisonjoseph are all of the broken links coming from pages that we have in this repo? Any broken links coming from remote MDX, where the fix would be setting additional redirects?

**Comment by alisonjoseph** [comment]
@mattrosno I also made a PR in the Carbon website repo to fix the broken links coming from remote pages https://github.com/carbon-design-system/carbon-website/pull/3167

**Review by francinelucca — APPROVED** [review]
LGTM!

**Review by andreancardona — APPROVED** [review]
nice!

**Pull request merged**
