### PR TITLE
fix(web-app): remove nav active state from section headings

### LINKED ISSUE #1287: Nav item shouldn't be "Active" when you open it but don't navigate to the page
**Bug🐛:** Nav item shouldn't be "Active" when you open it but don't navigate to the page
**Page:** https://next.carbondesignsystem.com/
**Suggestion:** I'm on the homepage, opened the "Designing" section and it set the active styles, it should only open the section, and set active when you are actually on that page. The headings that aren't pages shouldn't ever have the active state with the blue border to the left. See current Carbon website nav for example. 
Screen Shot 2022-09-16 at 9 41 49 AM

_Originally posted by @alisonjoseph in https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3663385_

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #1287

#### Changelog

**Changed**

- treeview nav styles

#### Testing / reviewing

Test navigation, section headings should no longer take on active class styles (no background or blue left border)

### CODE REVIEW

**Review by francinelucca — COMMENTED** [review]
is this PR supposed to leave the activeItem active or just remove the active state from the sections? I no longer see the active state on the sections but the active item's active state is also removed 🤔 
image

**Comment by alisonjoseph** [comment]
@francinelucca I'm still seeing the active state? It goes away when you open a section, but it does that currently also on the live site.

**Comment by francinelucca** [comment]
@alisonjoseph yeah I was just asking since now the active item won't be in the selected item, should the active item stay in the current page? and if so, is that in the scope of this ticket or is there another?

**Comment by francinelucca** [comment]
> @alisonjoseph yeah I was just asking since now the active item won't be in the selected item, should the active item stay in the current page? and if so, is that in the scope of this ticket or is there another?

Tracked in #1361 , this is good to go. Approving

**Review by francinelucca — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
tested and looks good!

**Pull request merged**
