### PR TITLE
feat(web-app): add library nav data to side nav

### LINKED ISSUE #556: Render library side nav items from schema
Once `navData` is available in the schema, read that to populate the side nav.

This is not building the actual pages, just the side nav and the links within.

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #556

#### Changelog

**Changed**

- Modified schema required logic for navData top-level items ( if items, path is not required, if path, items is not required)

#### Testing / reviewing

http://localhost:3000/assets/francine-test compare sidenav items to https://github.com/francinelucca/francine-test-library/blob/main/carbon.yml 

*** these will take you to 404 since we are not dynamically building these pages yet :D 
(will remove test lib on approval)

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Screen Shot 2022-06-02 at 3 57 23 PM

should  `hidden: true` be hiding that page?

**Comment by francinelucca** [comment]
> should `hidden: true` be hiding Test library page 2?

woooops, on it!

**Review by andreancardona — APPROVED** [review]
tested and checked at different breakpoints. Looks good! 🔥

**Review by alisonjoseph — APPROVED** [review]
sorry forgot to re-review this! Looks good 👍

**Pull request merged**
