### PR TITLE
docs: add library schema docs

### LINKED ISSUE #4: Document the schema structure and values
We'll need to document the schema(s) in terms of what they are, how to apply them, and the available values per property.

This could probably live in the top-level `/docs` directory in this repository for starters?

In the future, we might want to put the documentation into a package that we can independently version. Should we eventually ship it as a code package, that means we could deliver a script used by each repository to call in a pre-commit check where the script finds schemas and verifies that each Carbon config is valid.

A good example is the new GitHub issue templates. It states, "issue forms follow a schema, here's an example, here are the available keys, types, and value values."

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

### PR DESCRIPTION
**Pull request by mattrosno**
Closes #4

Adds documentation for how to add library and asset metadata files. Additional properties will be added in #6.

#### Changed

* Simplified the response of the image optimization
* Updated the prototype to use `thumbnailPath` instead of `thumbnail`

#### Review

Here's the markdown documentation.

https://github.com/carbon-design-system/carbon-platform/blob/b2e37d07d901f8e3f084c71a80ee484e9ca7f031/docs/resource-schemas.md

### CODE REVIEW

**Comment by mattrosno** [comment]
@andreancardona can you review this? In this first round of applying the schema to known libraries/assets, I'm thinking we'll just include the properties that I've documented in this PR: https://github.com/carbon-design-system/carbon-platform/blob/6607ad44c42b0b4b4f76152acff4a57e6e62bedf/docs/resource-schemas.md

Then after this feels good, via #6 we can add more properties to the schema, to the metadata files, then in the prototype.

**Comment by jdharvey-ibm** [comment]
@mattrosno Should we add a card to the backlog to turn the schemas into json/yaml schema files? If we have those on GitHub, they could be referenced by other projects to get code completion and property validation in real-time as they're being edited.

**Comment by mattrosno** [comment]
@jdharvey-ibm I don't follow your question. The application of the schema will take place in various repos in yml metadata files like this example: https://github.com/mattrosno/carbon-next/blob/e2f8bff6883f69a01feeb134b4b8a66414b5b07e/packages/react/src/components/Accordion/carbon-asset.yml

Our prototype is currently reading that YML data and parsing it into JSON.

**Comment by mattrosno** [comment]
@jdharvey-ibm bottom two issues in this epic will apply the schema for prototyping purposes.

https://github.com/carbon-design-system/carbon-platform/issues/2

**Comment by jdharvey-ibm** [comment]
@mattrosno Ah sorry, I'll try to clarify. I mean an actual formal json schema file that defines all possible fields that can exist in a `carbon-asset.yml` file or other file governed by a formal schema. This would be something like a `carbon-asset.schema.json` file that defines what fields are valid, what types they are, and where they can be used in one of the `carbon-asset.yml` files that an end user would place in their repo.

To use a schema, you include a line in your file to reference it, and from there, you get validation and auto-completion. Here's some pictures demoing me pulling in the example schema over at [json-schema.org](https://json-schema.org/learn/examples/address.schema.json)

image
image
image

**Comment by mattrosno** [comment]
@jdharvey-ibm got it - I'll document as a separate issue for schema tooling.

@andreancardona I added more documentation to describe value values: https://github.com/carbon-design-system/carbon-platform/blob/cdb912fa70c3cbe6dce4ddbef76bd7bb425e1b53/docs/resource-schemas.md

**Comment by mattrosno** [comment]
Markdown file has been updated: https://github.com/carbon-design-system/carbon-platform/blob/b2e37d07d901f8e3f084c71a80ee484e9ca7f031/docs/resource-schemas.md

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
