### PR TITLE
fix(web-app): library side nav style and spacing fix

### LINKED ISSUE #1059: Library side nav visual fixes
There are 2 visual bugs in the library side nav. Redlines for library (LHN is on the left side of file)

Hover state should be a link style:

add 8px padding under the Library Name and version bottom rule (above the assets button):

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #1059

#### Testing / reviewing

Check that spacing and link matches spec
http://localhost:3000/libraries/carbon-components-angular/latest/assets

### CODE REVIEW

**Review by francinelucca — COMMENTED** [review]
Lib nav LGTM, these changes also add an extra 8px top padding to the main nav, are we ok with that? 
image
image

**Comment by alisonjoseph** [comment]
Ahh good catch. I don't think so, I'll fix.

**Review by francinelucca — APPROVED** [review]
✨

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
it's looking good! the only thing that needs updating is that there seems to be a 1px gap between the vertical separating line and the back ground. 
image

**Review by andreancardona — APPROVED** [review]
approving - since I don't see the 1px bug mentioned above

**Comment by alisonjoseph** [comment]
Screen Shot 2022-08-09 at 10 55 14 AM

@kingtraceyj which browser are you in, and what page? @andreancardona and I are unable to duplicate.

**Comment by alisonjoseph** [comment]
Merging, @kingtraceyj we can't duplicate your error, but if you are still seeing it can you open a new issues with steps to duplicate?

**Pull request merged**
