### PR TITLE
fix: tree view style overrides

### LINKED ISSUE #1668: Extra spacing in sidenav
**Description**

Recent [style changes](https://github.com/carbon-design-system/carbon/pull/13354/files) in upstream carbon are making our overrides break the sidenav visuals. This is preventing deployment as we don't want to introduce these changes to production.

image

**Steps to reproduce**

https://next-test.carbondesignsystem.com/

Expand sidenav items and notice extra spacing

### PR DESCRIPTION
**Pull request by mattrosno**
Closes #1668 

Upstream component had styling changes so we have to modify our styling overrides

#### Changelog

**New**

- N/A

**Changed**

- Wrapped tree view in the g10 theme because that looks like a better starting point for overrides
- Tree view style overrides

**Removed**

- N/A

#### Testing / reviewing

Run locally and go to pages and subpages, desktop and mobile, and ensure that the side nav looks like the production site.

### CODE REVIEW

**Review by francinelucca — CHANGES_REQUESTED** [review]
This is almost there, I still see a bit of a jump when switching between prod and local, see screen record.

https://user-images.githubusercontent.com/40550942/233727961-1e82c534-710d-4061-a1fa-76c5ca71ee72.mov

**Comment by mattrosno** [comment]
@francinelucca thanks! I see one other issue that I need to look at. Adding is on the div not the anchor, so you can click the div and the tree view switches state, but navigation (via the anchor) doesn't execute.
image

**Comment by mattrosno** [comment]
@francinelucca can you give this another review? I wrapped the tree view in a g10 theme because that seems to be a better starting point for overrides (has a white background): https://react.carbondesignsystem.com/?path=/story/components-treeview--default&globals=theme:g10

I also took a fresh pass at all tree view overrides and added comments to all overrides so hopefully this is more maintainable going forward.

**Comment by alisonjoseph** [comment]
@mattrosno the Nav section headings (Catalogs, Collections) are a different color locally vs on the live site, probably due to the theme switch? Otherwise looks great!

**Comment by mattrosno** [comment]
@alisonjoseph oh I see that. Fixing now.

**Comment by mattrosno** [comment]
@alisonjoseph fixed.

**Review by alisonjoseph — APPROVED** [review]
🔥

**Review by francinelucca — CHANGES_REQUESTED** [review]
I still see a bit of a shift between prod/local 

https://user-images.githubusercontent.com/40550942/235250312-7f800c29-6b12-44c9-8bbe-80483a0c1f72.mov


https://user-images.githubusercontent.com/40550942/235250317-7d631309-51ef-4712-be27-97a35b70665a.mov

**Comment by mattrosno** [comment]
@francinelucca I believe prod is wrong. Notice how the baseline for "Developing" sits low on prod, and now it's properly vertically centered on local.
image

**Review by francinelucca — APPROVED** [review]

**Pull request merged**
