### PR TITLE
feat(web-app): add color-grid and color-block mdx components

### LINKED ISSUE #618: ColorBlock & ColorGrid MDX components
https://carbondesignsystem.com/guidelines/color/overview/#themes

`<ColorBlock size="xs">#ffffff</ColorBlock>`

```
<ColorGrid colorFamily="blue" />
<ColorGrid colorFamily="gray" />
<ColorGrid colorFamily="alerts" style="margin-top: 2rem" />
```

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #618

#### ColorBlock
http://localhost:3000/mdx/color-block
http://localhost:6006/?path=/docs/mdx-colorblock--default
https://carbondesignsystem.com/guidelines/color/overview/#themes

#### ColorGrid
http://localhost:3000/mdx/color-grid
http://localhost:6006/?path=/docs/mdx-colorgrid--default
https://carbondesignsystem.com/guidelines/color/overview/#color-anatomy

### CODE REVIEW

**Review by francinelucca — DISMISSED** [review]
LGTM

**Review by francinelucca — CHANGES_REQUESTED** [review]
minor CR

**Review by francinelucca — DISMISSED** [review]

**Review by francinelucca — DISMISSED** [review]
😻

**Review by francinelucca — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
Looks good!

**Pull request merged**
