### PR TITLE
feat(web-app): add dataviz pages

### LINKED ISSUE #916: Add data viz collection pages
**Summary**

Each collection has a list of resources, and also pages for supporting guidance. In a future release, we'll want to make this configurable so collections (specific to each system, global and local) can define its resources and also its pages through a `navData` construct.

For this first release, let's keep it simple and just add these three pages like our other static content.

In the future, we can give this more structure so collections can scale and not be hardcoded in this repo.

**Job stories**

What value will this deliver?

1. When browsing a collection, I want to view supporting documentation, so I can properly use the resources in the collection.

**Acceptance criteria**

What requirements must be met to complete this request?

1. All data viz content currently in https://carbondesignsystem.com is available through library or collection pages

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #916 
Add data viz collection pages

#### Changelog

**New**

- Data viz pages

  
Screen Shot 2022-06-24 at 1 30 31 PM

**Changed**

- fix for aside component styles 

#### Testing / reviewing

http://localhost:3000/data-visualization/axes-and-labels
http://localhost:3000/data-visualization/color-palettes
http://localhost:3000/data-visualization/chart-anatomy
http://localhost:3000/data-visualization/get-started
http://localhost:3000/data-visualization/legends
https://carbondesignsystem.com/data-visualization/dashboards/

### CODE REVIEW

**Review by francinelucca — COMMENTED** [review]
LGTM! couple links in charts-anatomy don't work but will be fixed if we add axes-and-labels and legends 👀

**Review by francinelucca — APPROVED** [review]
😻

**Comment by andreancardona** [comment]
@alisonjoseph I'm assuming this small bug should be opened up on the carbon repo, correct? `vanilla` -> `Vanilla`
Screen Shot 2022-06-28 at 5 15 54 PM

**Review by andreancardona — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@andreancardona yes that would be in the Carbon repo, however I'm not sure if vanilla should be capitalized, since its not a framework brand name like React, Angular.

**Pull request merged**
